const dotenv = require("dotenv");
const mongoose = require("mongoose");
const connectDB = require("./src/config/db");
const Property = require("./src/models/Property");

dotenv.config();

const properties = [
  {
    title: "Real House Luxury Villa",
    location: "Victoria Island, Lagos",
    city: "Victoria Island",
    state: "Lagos",
    price: "₦ 3,340,000,000",
    priceValue: 3340000000,
    bedrooms: 6,
    bathrooms: 3,
    status: "For Sale",
    featured: true,
    type: "Villa",
    image: "/public/images/properties/card-1.png",
    description:
      "A contemporary luxury villa in Victoria Island with expansive glass walls, open-plan living, and a poolside terrace perfect for entertaining.",
  },
  {
    title: "Exquisite Haven Villa",
    location: "Festac, Lagos",
    city: "Festac",
    state: "Lagos",
    price: "₦ 4,000,000 / 1 Year",
    priceValue: 4000000,
    bedrooms: 5,
    bathrooms: 3,
    status: "For Rent",
    featured: true,
    type: "Villa",
    image: "/public/images/properties/card-2.png",
    description:
      "Bright, airy interiors with a modern dining area, family-sized kitchen, and cozy lounge spaces ideal for long-term rental stays.",
  },
  {
    title: "Luxe Palatial Villa",
    location: "Gbagada, Lagos",
    city: "Gbagada",
    state: "Lagos",
    price: "₦ 5,350,000,000",
    priceValue: 5350000000,
    bedrooms: 7,
    bathrooms: 3,
    status: "For Sale",
    featured: true,
    type: "Villa",
    image: "/public/images/properties/card-3.png",
    description:
      "A grand multi-level palatial home in Gbagada with bold architecture, glass balconies, and premium finishings throughout.",
  },
  {
    title: "Harmony Luxury Villa",
    location: "Mushin, Lagos",
    city: "Mushin",
    state: "Lagos",
    price: "₦ 4,000,000 / 1 Year",
    priceValue: 4000000,
    bedrooms: 4,
    bathrooms: 3,
    status: "For Rent",
    featured: true,
    type: "Villa",
    image: "/public/images/properties/card-4.png",
    description:
      "A stylish villa with a private pool, large windows, and a seamless indoor-outdoor layout for comfortable family living.",
  },
  {
    title: "Real House Luxury Villa",
    location: "Victoria Island, Lagos",
    city: "Victoria Island",
    state: "Lagos",
    price: "₦ 350,000,000",
    priceValue: 350000000,
    bedrooms: 6,
    bathrooms: 4,
    status: "For Rent",
    featured: true,
    type: "Villa",
    image: "/public/images/properties/card-5.png",
    description:
      "Modern façade with clean lines, spacious bedrooms, and an extended backyard garden in the heart of Victoria Island.",
  },
  {
    title: "Real House Luxury Villa",
    location: "Lekki-Ajah, Lagos",
    city: "Lekki-Ajah",
    state: "Lagos",
    price: "₦ 4,200,000 / 1 Year",
    priceValue: 4200000,
    bedrooms: 5,
    bathrooms: 3,
    status: "For Rent",
    featured: true,
    type: "Villa",
    image: "/public/images/properties/card-6.png",
    description:
      "Premium waterfront-style villa in Lekki-Ajah with warm lighting, large terrace, and a stunning evening pool view.",
  },
  {
    title: "Infinite Bliss Villa",
    location: "Ishiagu, Enugu",
    city: "Ishiagu",
    state: "Enugu",
    price: "₦ 2,350,000,000",
    priceValue: 2350000000,
    bedrooms: 5,
    bathrooms: 3,
    status: "For Sale",
    featured: true,
    type: "Villa",
    image: "/public/images/properties/card-7.png",
    description:
      "Contemporary multi-storey villa with bold architecture, balconies, and lush landscaping in a serene Ishiagu neighbourhood.",
  },
  {
    title: "Real House Luxury Villa",
    location: "Works Layout, Owerri",
    city: "Owerri",
    state: "Imo",
    price: "₦ 3,350,000 / 1 Year",
    priceValue: 3350000,
    bedrooms: 8,
    bathrooms: 6,
    status: "For Rent",
    featured: true,
    type: "Villa",
    image: "/public/images/properties/card-8.png",
    description:
      "Large family villa with extensive lawn, multiple bedrooms, and a classic exterior located in Works Layout, Owerri.",
  },
  {
    title: "Real House Luxury Villa",
    location: "Ikeja, Lagos",
    city: "Ikeja",
    state: "Lagos",
    price: "₦ 600,000,000",
    priceValue: 600000000,
    bedrooms: 6,
    bathrooms: 6,
    status: "For Sale",
    featured: true,
    type: "Villa",
    image: "/public/images/properties/card-9.png",
    description:
      "Charming suburban-style villa in Ikeja with spacious interiors, garage, and a well-kept front yard in a quiet estate.",
  },

  {
    title: "Luxury 4 Bedroom Duplex",
    location: "Lekki Phase 1, Lagos",
    price: "45000000 / 1 year",
    priceValue: 45000000,
    bedrooms: 4,
    bathrooms: 4,
    status: "For Rent",
    featured: true,
    image: "https://images.pexels.com/photos/280229/pexels-photo-280229.jpeg",
    city: "Lekki",
    state: "Lagos",
    type: "Duplex",
    description: "A luxurious duplex with modern finishing and ample parking.",
  },
  {
    title: "Modern 3 Bedroom Apartment",
    location: "Gbagada, Lagos",
    price: "25000000 / 1 year",
    priceValue: 25000000,
    bedrooms: 3,
    bathrooms: 3,
    status: "For Rent",
    featured: false,
    image: "https://images.pexels.com/photos/271642/pexels-photo-271642.jpeg",
    city: "Gbagada",
    state: "Lagos",
    type: "Apartment",
    description:
      "A spacious and well-lit 3 bedroom apartment in a serene area.",
  },
  {
    title: "5 Bedroom Luxury Mansion",
    location: "Ikoyi, Lagos",
    price: "750000000",
    priceValue: 750000000,
    bedrooms: 5,
    bathrooms: 6,
    status: "For Sale",
    featured: true,
    image: "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg",
    city: "Ikoyi",
    state: "Lagos",
    type: "Mansion",
    description:
      "High-end mansion located in the heart of Ikoyi with premium facilities.",
  },
  {
    title: "Compact 2 Bedroom Flat",
    location: "Surulere, Lagos",
    price: "1500000 / 1 year",
    priceValue: 1500000,
    bedrooms: 2,
    bathrooms: 2,
    status: "For Rent",
    featured: false,
    image: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg",
    city: "Surulere",
    state: "Lagos",
    type: "Flat",
    description:
      "Affordable and comfortable 2 bedroom flat close to major roads.",
  },
  {
    title: "Beachfront 4 Bedroom Villa",
    location: "Oniru, Lagos",
    price: "320000000",
    priceValue: 320000000,
    bedrooms: 4,
    bathrooms: 5,
    status: "For Sale",
    featured: true,
    image: "https://images.pexels.com/photos/2102587/pexels-photo-2102587.jpeg",
    city: "Oniru",
    state: "Lagos",
    type: "Villa",
    description:
      "A stunning villa overlooking the Atlantic with luxury amenities.",
  },
  {
    title: "Affordable Mini Flat",
    location: "Ojota, Lagos",
    price: "800000 / 1 year",
    priceValue: 800000,
    bedrooms: 1,
    bathrooms: 1,
    status: "For Rent",
    featured: false,
    image: "https://images.pexels.com/photos/259950/pexels-photo-259950.jpeg",
    city: "Ojota",
    state: "Lagos",
    type: "Mini Flat",
    description:
      "Mini flat suitable for young professionals or small families.",
  },
  {
    title: "Exquisite 3 Bedroom Terrace",
    location: "Chevron Drive, Lekki",
    price: "38000000",
    priceValue: 38000000,
    bedrooms: 3,
    bathrooms: 4,
    status: "For Sale",
    featured: false,
    image: "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg",
    city: "Lekki",
    state: "Lagos",
    type: "Terrace",
    description:
      "A beautiful terrace with modern interiors and tight security.",
  },
  {
    title: "Classic 4 Bedroom Bungalow",
    location: "Magodo Phase 2, Lagos",
    price: "32000000",
    priceValue: 32000000,
    bedrooms: 4,
    bathrooms: 4,
    status: "For Sale",
    featured: false,
    image: "https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg",
    city: "Magodo",
    state: "Lagos",
    type: "Bungalow",
    description: "A well-built bungalow in a serene gated estate.",
  },
  {
    title: "Newly Built 2 Bedroom Apartment",
    location: "Yaba, Lagos",
    price: "2500000 / 1 year",
    priceValue: 2500000,
    bedrooms: 2,
    bathrooms: 2,
    status: "For Rent",
    featured: true,
    image: "https://images.pexels.com/photos/271618/pexels-photo-271618.jpeg",
    city: "Yaba",
    state: "Lagos",
    type: "Apartment",
    description:
      "Perfect for students and young families with great accessibility.",
  },
  {
    title: "Luxury Waterfront Penthouse",
    location: "Eko Atlantic, Lagos",
    price: "950000000",
    priceValue: 950000000,
    bedrooms: 5,
    bathrooms: 6,
    status: "For Sale",
    featured: true,
    image: "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg",
    city: "Victoria Island",
    state: "Lagos",
    type: "Penthouse",
    description: "A stunning penthouse with panoramic ocean views.",
  },
  {
    title: "3 Bedroom Semi-Detached Duplex",
    location: "Ogudu GRA, Lagos",
    price: "42000000",
    priceValue: 42000000,
    bedrooms: 3,
    bathrooms: 3,
    status: "For Sale",
    featured: false,
    image: "https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg",
    city: "Ogudu",
    state: "Lagos",
    type: "Duplex",
    description: "Located in a high-demand area with good road network.",
  },
  {
    title: "Standard 2 Bedroom Flat",
    location: "Abule Egba, Lagos",
    price: "1200000 / 1 year",
    priceValue: 1200000,
    bedrooms: 2,
    bathrooms: 2,
    status: "For Rent",
    featured: false,
    image: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg",
    city: "Abule Egba",
    state: "Lagos",
    type: "Flat",
    description: "Affordable housing option in a calm residential environment.",
  },
  {
    title: "Premium Office Space",
    location: "Victoria Island, Lagos",
    price: "15000000 / 1 year",
    priceValue: 15000000,
    bedrooms: 1,
    bathrooms: 2,
    status: "For Rent",
    featured: true,
    image: "https://images.pexels.com/photos/273209/pexels-photo-273209.jpeg",
    city: "Victoria Island",
    state: "Lagos",
    type: "Commercial",
    description: "A modern office space suitable for corporate businesses.",
  },
  {
    title: "Fully Furnished Studio Apartment",
    location: "Ikeja GRA, Lagos",
    price: "3500000 / 1 year",
    priceValue: 3500000,
    bedrooms: 1,
    bathrooms: 1,
    status: "For Rent",
    featured: false,
    image: "https://images.pexels.com/photos/271639/pexels-photo-271639.jpeg",
    city: "Ikeja",
    state: "Lagos",
    type: "Studio",
    description: "Ideal for short stays with all amenities included.",
  },
  {
    title: "5 Bedroom Detached Duplex",
    location: "Osapa London, Lekki",
    price: "180000000",
    priceValue: 180000000,
    bedrooms: 5,
    bathrooms: 6,
    status: "For Sale",
    featured: true,
    image: "https://images.pexels.com/photos/280229/pexels-photo-280229.jpeg",
    city: "Lekki",
    state: "Lagos",
    type: "Duplex",
    description: "Spacious duplex with modern facilities and swimming pool.",
  },
  {
    title: "Self-Contained Apartment",
    location: "Shomolu, Lagos",
    price: "700000 / 1 year",
    priceValue: 700000,
    bedrooms: 1,
    bathrooms: 1,
    status: "For Rent",
    featured: false,
    image: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg",
    city: "Shomolu",
    state: "Lagos",
    type: "Self-Contain",
    description: "Affordable and clean self-contained in central location.",
  },
  {
    title: "Luxury Duplex with BQ",
    location: "Ajah, Lagos",
    price: "60000000",
    priceValue: 60000000,
    bedrooms: 4,
    bathrooms: 5,
    status: "For Sale",
    featured: false,
    image: "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg",
    city: "Ajah",
    state: "Lagos",
    type: "Duplex",
    description: "A newly built house with boys quarters and CCTV.",
  },
  {
    title: "3 Bedroom Furnished Apartment",
    location: "Maryland, Lagos",
    price: "4200000 / 1 year",
    priceValue: 4200000,
    bedrooms: 3,
    bathrooms: 3,
    status: "For Rent",
    featured: true,
    image: "https://images.pexels.com/photos/271642/pexels-photo-271642.jpeg",
    city: "Maryland",
    state: "Lagos",
    type: "Apartment",
    description: "Fully furnished apartment near major business districts.",
  },
  {
    title: "4 Bedroom Townhouse",
    location: "Banana Island, Lagos",
    price: "650000000",
    priceValue: 650000000,
    bedrooms: 4,
    bathrooms: 5,
    status: "For Sale",
    featured: true,
    image: "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg",
    city: "Ikoyi",
    state: "Lagos",
    type: "Townhouse",
    description: "Premium townhouse inside a high-end community.",
  },
  {
    title: "Modern Detached Duplex",
    location: "Sangotedo, Lagos",
    price: "35000000",
    priceValue: 35000000,
    bedrooms: 4,
    bathrooms: 4,
    status: "For Sale",
    featured: false,
    image: "https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg",
    city: "Sangotedo",
    state: "Lagos",
    type: "Duplex",
    description: "A beautiful newly constructed duplex in a gated estate.",
  },
  {
    title: "Affordable Studio Room",
    location: "Egbeda, Lagos",
    price: "600000 / 1 year",
    priceValue: 600000,
    bedrooms: 1,
    bathrooms: 1,
    status: "For Rent",
    featured: false,
    image: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg",
    city: "Egbeda",
    state: "Lagos",
    type: "Studio",
    description: "Clean and budget-friendly studio apartment.",
  },
  {
    title: "Furnished 2 Bedroom Apartment",
    location: "Ilasan, Lekki",
    price: "3000000 / 1 year",
    priceValue: 3000000,
    bedrooms: 2,
    bathrooms: 2,
    status: "For Rent",
    featured: true,
    image: "https://images.pexels.com/photos/271639/pexels-photo-271639.jpeg",
    city: "Lekki",
    state: "Lagos",
    type: "Apartment",
    description: "Fully furnished apartment suitable for families.",
  },
  {
    title: "Brand New 4 Bedroom Terrace",
    location: "Chevron Drive, Lekki",
    price: "52000000",
    priceValue: 52000000,
    bedrooms: 4,
    bathrooms: 4,
    status: "For Sale",
    featured: false,
    image: "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg",
    city: "Chevron",
    state: "Lagos",
    type: "Terrace",
    description: "Modern terrace with elegant finishing in a calm environment.",
  },
  {
    title: "Luxury Skyscraper Apartment",
    location: "Oniru, Lagos",
    price: "32000000 / 1 year",
    priceValue: 32000000,
    bedrooms: 3,
    bathrooms: 4,
    status: "For Rent",
    featured: true,
    image: "https://images.pexels.com/photos/2102587/pexels-photo-2102587.jpeg",
    city: "Oniru",
    state: "Lagos",
    type: "Highrise",
    description: "Apartment in a tall modern skyscraper with amazing views.",
  },
  {
    title: "Simple 2 Bedroom Home",
    location: "Ikorodu, Lagos",
    price: "900000 / 1 year",
    priceValue: 900000,
    bedrooms: 2,
    bathrooms: 2,
    status: "For Rent",
    featured: false,
    image: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg",
    city: "Ikorodu",
    state: "Lagos",
    type: "House",
    description: "A simple but neat 2 bedroom home for small families.",
  },
  {
    title: "Elegant 3 Bedroom Condo",
    location: "Victoria Island, Lagos",
    price: "350000000",
    priceValue: 350000000,
    bedrooms: 3,
    bathrooms: 3,
    status: "For Sale",
    featured: true,
    image: "https://images.pexels.com/photos/271642/pexels-photo-271642.jpeg",
    city: "Victoria Island",
    state: "Lagos",
    type: "Condo",
    description: "Luxury condo inside a fully serviced building.",
  },
];

const run = async () => {
  try {
    await connectDB();
    await Property.deleteMany();
    await Property.insertMany(properties);
    console.log("Properties seeded");
    process.exit();
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
};

run();
